version: '3.8'
services:
  github-runner:
    image: myoung34/github-runner:latest  # Popular image for GitHub runners
    environment:
      - RUNNER_NAME=local-runner
      - RUNNER_TOKEN=${RUNNER_TOKEN}  # Will be set dynamically
      - REPO_URL=https://github.com/stainley/CareerLaunch
      - LABELS=local,java21,maven  # Custom labels for the runner
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Allows Docker-in-Docker (optional)
    network_mode: host
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"  # Exposes SonarQube UI and API
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true  # Disables ES bootstrap checks
    volumes:
      - sonarqube_data:/opt/sonarqube/data  # Persists SonarQube data
      - sonarqube_logs:/opt/sonarqube/logs  # Persists logs
      - sonarqube_extensions:/opt/sonarqube/extensions  # For plugins
    #network_mode: host  # Ensures SonarQube is accessible on localhost:9000
    restart: unless-stopped

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: