# Eureka Server Configuration (High Availability-Ready)
EUREKA_USER: your_username
EUREKA_PASSWORD: your_password
EUREKA_ENVIRONMENT: prod
RENEWS_THRESHOLD: 0.85
EUREKA_DATA_CENTER: Azure


# Security Configuration Recommendations:
# 1. Enable HTTPS for production environments
# 2. Rotate credentials regularly
# 3. Use encrypted configuration for credentials
# 4. Implement IP whitelisting for peer communication

# Peer Awareness Configuration (For HA Cluster):
# Uncomment and modify for multi-node deployment
# eureka:
#   client:
#     service-url:
#       defaultZone: http://peer1:8761/eureka/,http://peer2:8761/eureka/
