server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: auth-server
            uri: lb://AUTH-SERVER
            predicates:
              - Path=/users/**


eureka:
  instance:
    appname: api-gateway
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
