name: Backend CI

on:
  push:
    branches-ignore: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: [ self-hosted, local, java21, maven ]
    strategy:
      matrix:
        service: [ shared-library, notification-service ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.6'

      - name: Debug SonarQube URL
        run: echo "SONAR_HOST_URL is $LOCAL_SONAR_HOST_URL"

      - name: Build Shared Library
        run: |
          cd backend/shared-library
          mvn clean install -DskipTests

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/${{ matrix.service }}/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: |
          cd backend/${{ matrix.service }}
          mvn clean install -DskipTests=false

      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.LOCAL_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.LOCAL_SONAR_HOST_URL }}
        run: |
          cd backend/${{ matrix.service }}
          mvn sonar:sonar \
            -Dsonar.projectKey=com.salapp.career.launch:${{ matrix.service }} \
            -Dsonar.projectName="${{ matrix.service }}" \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.token=${SONAR_TOKEN}

      - name: Check SonarQube Quality Gate Status
        env:
          SONAR_TOKEN: ${{ secrets.LOCAL_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.LOCAL_SONAR_HOST_URL }}
        run: |
          # Set environment variables for debugging
          Write-Host "SONAR_TOKEN: $env:SONAR_TOKEN"
          Write-Host "SONAR_HOST_URL: $env:SONAR_HOST_URL"
          
          # Initialize the status variable
          $quality_gate_status = "PENDING"
          $maxRetries = 30
          $retryCount = 0
          
          $Headers = @{
            Authorization = "Bearer $env:SONAR_TOKEN"
          }
          
          Write-Host "Header is: $Headers"
          Write-Host "TOKEN = ${env:SONAR_TOKEN}"
          
          # Poll for the quality gate status
          while ($quality_gate_status -eq "PENDING" -and $retryCount -lt $maxRetries) {
            # Query the SonarQube API to get the quality gate status
            $url = "$env:SONAR_HOST_URL/api/qualitygates/project_status?projectKey=bank-showcase"
            Write-Host "HOST URL = $url"
          
            try {
                # Get the raw response using Invoke-RestMethod
                $response = Invoke-RestMethod -Uri $url -Headers $Headers -ErrorAction Stop
          
                Write-Host "Raw API Response: $response"
          
                # Retrieve quality gate status
                $quality_gate_status = $response.projectStatus.status
                Write-Host "Quality Gate Status: $quality_gate_status"
          
            } catch {
                Write-Host "Error encountered: $_"
                exit 1
            }
          
            # Wait before the next retry
            Start-Sleep -Seconds 10
            $retryCount++
          }
          
          if ($quality_gate_status -ne "OK") {
              Write-Host "Quality Gate failed or timeout reached"
              exit 1  # Fail the job if the quality gate is not OK
          }
  sonar-main:
    runs-on: [ self-hosted, local, java21, maven ]
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'
    strategy:
      matrix:
        service: [ notification-service ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.9.6'

      - name: Build Shared Library
        run: |
          cd backend/shared-library
          mvn clean install -DskipTests

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('backend/${{ matrix.service }}/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and Test with Maven
        run: |
          cd backend/${{ matrix.service }}
          mvn clean install -DskipTests=false

      - name: SonarQube Scan (Main Branch)
        env:
          SONAR_TOKEN: ${{ secrets.LOCAL_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.LOCAL_SONAR_HOST_URL }}
        run: |
          cd backend/${{ matrix.service }} && \
          mvn sonar:sonar \
            -Dsonar.projectKey=com.salapp.career.launch:${{ matrix.service }} \
            -Dsonar.projectName="${{ matrix.service }}" \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.token=${SONAR_TOKEN}
            -Dsonar.branch.name=${{ github.ref_name }}

      - name: Check SonarCloud Quality Gate Status (Main Branch)
        env:
          SONAR_TOKEN: ${{ secrets.LOCAL_SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.LOCAL_SONAR_HOST_URL }}
        run: |
          PROJECT_KEY="com.salapp.career.launch:${{ matrix.service }}"
          BRANCH_NAME=${{ github.ref_name }}
          
          # Query SonarCloud API for Quality Gate status
          STATUS=$(curl -u "${SONAR_TOKEN}:" -s \
            "${SONAR_HOST_URL}/api/qualitygates/project_status?projectKey=${PROJECT_KEY}&branch=${BRANCH_NAME}" | \
            jq -r '.projectStatus.status')
          
          echo "Quality Gate Status: $STATUS"
          
          # Fail the job if Quality Gate status is not OK
          if [ "$STATUS" != "OK" ]; then
            echo "Quality Gate failed for ${PROJECT_KEY} on branch ${BRANCH_NAME}"
            exit 1
          fi

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        service: [ service-discovery, shared-library, user-service, api-gateway, notification-service, auth-server ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build JAR
        run: |
          cd backend/${{ matrix.service }}
          mvn package -DskipTests=true

      - name: Deploy JAR
        run: |
          scp backend/${{ matrix.service }}/target/*.jar user@your-server:/path/to/deploy
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}